services:
  db:
    image: postgres:14.3
    restart: always
    ports:
      - "5432:5432"
    environment: 
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    container_name: pancaserodb
    volumes:
      - ./postgres:/var/lib/postgresql/data

  keycloak:
    image: quay.io/keycloak/keycloak:26.2.0
    container_name: keycloak-1
    command: start-dev
    ports:
      - "8080:8080"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    volumes:
      - ./keycloak-data:/opt/keycloak/data
  